bids_dir: '/path/to/bids_dir'
output_dir: '/path/to/output_dir'

# Resources
processes: 16
memory: 64000
local_scratch: '/tmp'
local_scratch_env: 'SLURM_TMPDIR'

#enable printing debug statements during parsing -- disable if generating dag visualization
debug: False

derivatives: False #will search in bids/derivatives if True; can also be path(s) to derivatives datasets

#list of analysis levels in the bids app
analysis_levels: &analysis_levels
 - participant


#mapping from analysis_level to set of target rules or files
targets_by_analysis_level:
  participant:
    - ''  # if '', then the first rule is run

#this configures the pybids grabber - create an entry for each type of input you want to grab
# indexed by name of input
#   dictionary for each input is passed directly to pybids get()
#    https://bids-standard.github.io/pybids/generated/bids.layout.BIDSLayout.html#bids.layout.BIDSLayout.get

pybids_inputs:
  ieeg:
    filters:
      suffix: 'ieeg'
      extension: '.edf'
      datatype: 'ieeg'
      task: 'full'
    wildcards:
      - subject
      - session
      - acquisition
      - task
      - run
  
  annotations:
    filters:
      suffix: 'annotations'
      extension: '.tsv'
      datatype: 'ieeg'
    wildcards:
      - subject
      - session
      - acquisition
      - task
      - run
  
  seega_tsv:
    filters:
      suffix: 'native_SEEG'
      space: 'native'
      extension: '.tsv'
    wildcards:
      - subject
      - session
      - acquisition
      - task
      - run
    custom_path: '/home/mcesped/projects/ctb-akhanf/cfmm-bids/Khan/clinical_imaging/epi_iEEG/old_bids/derivatives/seega_coordinates/sub-P{subject}/sub-P{subject}_space-native_SEEGA.tsv'

  parc:
    filters:
      suffix: 'orig'
      extension: '.mgz'
    wildcards:
      - subject
      - session
      - acquisition
      - task
      - run
    custom_path: /home/mcesped/projects/ctb-akhanf/cfmm-bids/Khan/clinical_imaging/epi_iEEG/old_bids/derivatives/fastsurfer/sub-P{subject}/mri/aparc+aseg{extension}

  tf:
    filters:
      suffix: 'ras_xfm'
      extension: '.txt'
    wildcards:
      - subject
      - session
      - acquisition
      - task
      - run
    custom_path: '/home/mcesped/projects/ctb-akhanf/cfmm-bids/Khan/clinical_imaging/epi_iEEG/old_bids/derivatives/atlasreg/sub-P{subject}/sub-P{subject}_desc-rigid_from-noncontrast_to-contrast_type-ras_xfm.txt'
    # custom_path: '/home/mcesped/projects/ctb-akhanf/cfmm-bids/Khan/clinical_imaging/epi_iEEG/old_bids/derivatives/atlasreg/sub-P{subject}/sub-P{subject}_acq-noncontrast_desc-rigid_from-noncontrast_to-contrast_type-ras_xfm.txt'

  T1w:
    filters:
      suffix: 'T1w'
      extension: '.nii.gz'
    wildcards:
      - subject
      - session
      - acquisition
      - task
      - run
    custom_path: '/project/ctb-akhanf/cfmm-bids/Khan/clinical_imaging/epi_iEEG/old_bids/derivatives/atlasreg/sub-P{subject}/sub-P{subject}_T1w.nii.gz'

freesurf_dir: None #'/home/mcesped/projects/ctb-akhanf/cfmm-bids/Khan/clinical_imaging/epi_iEEG/old_bids/derivatives/fastsurfer/'
freesurf_patient_label: None #'sub-P{subject}'

# ---------------- Pipeline parameters-------------------
# 1. Parameters for downsampling step:
# (1.a) Target sampling rate
# Default: 200 Hz
target_srate: 200


# 2. Parameters for filtering step:
# (2.a) Detrend method 
# Options: 'LinearDetrend','HighPass' (default), 'Demean'
detrend_method: 'HighPass'

# (2.b) Power line interference removal method
# Options: 'Cleanline', 'Zapline', 'NotchFilter' (default), 'PLIremoval'
methodPLI: 'Cleanline'

# (2.c) Electrical grid fundamental frequency
# Default: 60 Hz  
lineFreq: 60

# (2.d) Bandwidth for Notch filter (TODO) or Cleanline
# Note: in 'Cleanline', the bandwidth represents the frequency range 
# (around the theoretical fundamental and harmonic frequencies) in which
# to search for possible peaks associated with line noise. 
# Default: 4 (ex: if lineFreq=60, the range would go from 58 to 62)
bandwidth: 8

# (2.e) Number of harmonics to remove when using Notch Filter
# Default: 1 (only removes fundamental frequency)
n_harmonics: 1

# (2.f) Boolean to define whether to run autoreject to find noisy segments
# of data or not. 
# Default: True (runs autoreject)
noiseDetect: False

# (2.g) Transition band of high pass filter used in detrending step (if selected)
highpass: [0.1, 0.2]

# (2.h) Maximum duration of a flat line for a channel to be classified as clean
maxFlatlineDuration: 5 

# (2.i) Length of epochs to run Autoreject (in seconds).
# Default: 5 seconds
epoch_length: 5 


# 3. Parameters for region identification step
# (3.1) Boolean to discard signals from electrodes located in white matter or 
# 'unknown' region
# Default: True (discards the signals)
discard_wm_un: True


# 4. Parameter for regions identification and rereferencing step 
# (4.1) Column names in tsv file with electrodes information
# Format: [{type of channel}, {channel label}, {x position}, {y position}, {z position}, {group}]
# Default: ['type', 'label', 'x', 'y', 'z', 'group'] or None (both options are equivalent)
tsv_cols: ['type', 'label', 'x', 'y', 'z', 'orig_group']

# Space to identify regions: 'subject' or 'MNI'
space_regions: 'MNI'

t1_to_coords_tfm: False 
# Transform is not required in my case as I'm using T1w.nii.gz file, which is always in
# the same position as the electrodes coordinates (contrast space)

# Templates
# template: MNI152NLin2009cAsym
# template_t1w: resources/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz
# template_mask: resources/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_desc-brain_mask.nii.gz 
template: MNI152NLin2009cSym
template_t1w: resources/tpl-MNI152NLin2009cSym/tpl-MNI152NLin2009cSym_res-1_T1w.nii.gz
template_mask: resources/tpl-MNI152NLin2009cSym/tpl-MNI152NLin2009cSym_res-1_desc-brain_mask.nii.gz 
# template: MNI305
# template_t1w: resources/tpl-MNI305/tpl-MNI305_T1w.nii.gz
# template_mask: resources/tpl-MNI305/tpl-MNI305_desc-brain_mask.nii.gz 
atlas_template: resources/tpl-MNI152NLin2009cSym/atlas/aal116_roi_atlas.nii
colortable: resources/tpl-MNI152NLin2009cSym/atlas/aal_labels.tsv


#-------------------------------BIDS APP Configuration---------------------------
#this configures the options to save the BIDSLayout
# by default, database is not saved (uncomment to save)
# NOTE: pybids_db_dir must be an absolute path
# pybids_db_dir: '/path/to/db_dir' # Leave blank if you do not wish to use this
# pybids_db_reset: False # Change this to true to update the database

#configuration for the command-line parameters to make available
# passed on the argparse add_argument()
parse_args:

#---  core BIDS-app options --- (do not modify below)

  bids_dir:
    help: The directory with the input dataset formatted according
          to the BIDS standard.

  output_dir:
    help: The directory where the output files
          should be stored. If you are running group level analysis
          this folder should be prepopulated with the results of the
          participant level analysis.

  analysis_level:
    help: Level of the analysis that will be performed.
    choices: *analysis_levels

  --participant_label:
    help: The label(s) of the participant(s) that should be analyzed. The label
          corresponds to sub-<participant_label> from the BIDS spec
          (so it does not include "sub-"). If this parameter is not
          provided all subjects should be analyzed. Multiple
          participants can be specified with a space separated list.
    nargs: '+'

  --exclude_participant_label:
    help: The label(s) of the participant(s) that should be excluded. The label
          corresponds to sub-<participant_label> from the BIDS spec
          (so it does not include "sub-"). If this parameter is not
          provided all subjects should be analyzed. Multiple
          participants can be specified with a space separated list.
    nargs: '+'

  --derivatives:
    help: 'Path(s) to a derivatives dataset, for folder(s) that contains multiple derivatives datasets (default: %(default)s) '
    default: False
    nargs: '+'

  --run_all:
    help: 'Run complete preprocessing pipeline: downsampling, cleaning and rereferencing.'
    default: false
    action: store_true

  --epoch:
    help: 'Extract epochs from a given edf file.'
    default: false
    action: store_true

  --downsample:
    help: 'Downsample a given edf file.'
    default: false
    action: store_true

  --filter:
    help: 'Filter a given edf file (detrending and noise detection).'
    default: false
    action: store_true
  
  --rereference:
    help: 'Rereference a given unipolar edf file to bipolar.'
    default: false
    action: store_true

  --PLI_rej:
    help: 'Power Line Noise rejection given an edf file.'
    default: false
    action: store_true

  --regions_id:
    help: 'Identify regional location of electrodes given edf file and discard white matter and unknown categories.'
    default: false
    action: store_true

  --anat:
    help: 'Segmentation and preprocessing of T1w.'
    default: false
    action: store_true

  --graham:
    help: 'Use containers on compute canada graham.'
    default: false
    action: store_true
  
  --fs_license:
    help: 'Provide path to freesurfer license text file.'
    default: false
    required: false
    nargs: 1
 # custom command-line parameters can then be added, these will get added to the config
 # below is an example to override config['bet_frac']
#   --smoothing_fwhm:
#       nargs: '+'
#       required: True


# #--- workflow specific configuration -- below is just an example:


#singularity containers
singularity:
    graham:
      diffparc: '/project/ctb-akhanf/akhanf/singularity/bids-apps/khanlab_diffparc-deps_v0.1.0-fix.sif'
      fmriprep: '/project/6050199/akhanf/singularity/bids-apps/poldracklab_fmriprep_20.1.1.sif' 
    docker:
      diffparc: 'docker://khanlab/diffparc-deps:v0.1.0-fix'
      fmriprep: docker://nipreps/fmriprep:22.0.1'
