clear;clc;
load('~/scratch/code/sEEGPrep/notebooks/PLI_test_signals.mat')


% -------------------------------Case A ----------------------------------
%% Run cleanline
signals = [];
signals.data = eeg_signal_a';
sr = 400;
signals.srate = 200;
lineNoiseIn = struct('lineNoiseMethod', 'clean', ...
        'lineNoiseChannels', 1:size(eeg_signal_a',1),...
        'Fs', sr, ...
        'lineFrequencies', [60],...
        'p', 0.01, ...
        'fScanBandWidth', 8, ...
        'taperBandWidth', 2, ...
        'taperWindowSize', 4, ...
        'taperWindowStep', 1, ...
        'tau', 100, ...
        'pad', 2, ...
        'fPassBand', [0 100], ...
        'maximumIterations', 10);
[y2, lineNoiseOut] = cleanLineNoise(signals, lineNoiseIn);
y2 = y2.data;
y2 = y2';

%% Run Zapline
% apply nt_zapline
FLINE=60/sr; % line frequency
NREMOVE=1; % number of components to remove
[y1,~]= nt_zapline(eeg_signal_a,FLINE,NREMOVE);

%% Run removePLI
y3 = zeros(size(y1));
for i = 1:size(y1,2)
    y3(:,i) = removePLI(eeg_signal_a(:,i), sr, 3,[100, 0.01, 4],[0.1, 2, 5], 2, 60);
end